---
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and test workflow
on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Install non-python dependencies
        run: |
          sudo apt-get install -y graphviz-dev

      - name: Setup Python environment
        uses: khanlab/actions/.github/actions/action-setup_task-installPyProject@v0.3.2
        with:
          python-version: "3.11"

      - name: isort
        run: poetry run isort ngs_pipeline/*.py -c

      - name: Black
        run: poetry run black ngs_pipeline --check

      - name: snakefmt
        run: poetry run snakefmt ngs_pipeline --check

  test:
    runs-on: ubuntu-latest
    needs: ["quality"]
    defaults:
      run:
        shell: bash -l {0}
          

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Miniforge and mamba
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          mamba-version: "*"
          use-mamba: true
          conda-solver: libmamba
          auto-activate-base: true

      - name: Install snakebids
        run: |
          mamba install snakebids -c bioconda -c conda-forge -y

      - name: Test
        run: |
          ./ngs_pipeline/run.py tests/data test_out participant -np